version: '3.8'

services:
  n8n:
    build: .
    ports:
      - "80:5678"
    environment:
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-https}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE:-false}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}  # Obligatorio
      # Configuración de la base de datos
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${DB_NAME:-n8n}
      - DB_POSTGRESDB_USER=${DB_USER:-postgres}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}  # Obligatorio
      - DB_POSTGRESDB_HOST=${DB_HOST:-postgres}
      - DB_POSTGRESDB_PORT=${DB_PORT:-5432}

      - N8N_DB_SSL=true  # Obligatorio para Render.io
      - NODE_TLS_REJECT_UNAUTHORIZED=0  # Solo para testing (elimínalo después)
      - DEBUG=pg*, sequelize*
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network


volumes:
  n8n_data:

networks:
  n8n_network: